version: "3.8"
services:
  web:
    build: .
    container_name: markchecker_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3


